import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next Goodpharm",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className="antialiased"
        style={{ fontFamily: 'Pretendard Variable' }}
      >
        {children}
      </body>
    </html>
  );
}
